# Generated by Django 4.2.3 on 2023-08-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='cap',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='places',
            name='days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='places',
            name='name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='places',
            name='offer',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='places',
            name='review',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
