# Generated by Django 4.2.3 on 2023-08-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a2', '0002_places_cap_places_days_places_name_places_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
